wget -q -S -O - https://stage.aionianbible.org
wget -q -S -O - https://stage.aionianbible.org/Bogus
wget -q -S -O - https://stage.AionianBible.org/Preface
wget -q -S -O - https://stage.AionianBible.org/Buy
wget -q -S -O - https://stage.AionianBible.org/Aionios-and-Aidios
wget -q -S -O - https://stage.AionianBible.org/Glossary
wget -q -S -O - https://stage.AionianBible.org/Read
wget -q -S -O - https://stage.AionianBible.org/Readers-Guide
wget -q -S -O - https://stage.AionianBible.org/History
wget -q -S -O - https://stage.AionianBible.org/Maps
wget -q -S -O - https://stage.AionianBible.org/Publisher
wget -q -S -O - https://stage.AionianBible.org/Promote
wget -q -S -O - https://stage.AionianBible.org/Bible-Cover
wget -q -S -O - https://stage.AionianBible.org/Apple-iOS-App
wget -q -S -O - https://stage.AionianBible.org/Third-Party-Publisher-Resources

wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h1
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h2
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h3
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h4
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h5
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h6
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h7
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h8
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h9
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-h10

wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g1
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g2
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g3
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g4
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g5
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g6
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g7
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g8
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g9
wget -q -S -O - https://stage.aionianbible.org/Strongs/strongs-g10

wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Noted
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Old
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/New
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/37/35/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/42/38/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/44/29/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/44/31/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Numbers/16/30/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Numbers/16/33/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Deuteronomy/32/22/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Samuel/2/6/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Samuel/22/6/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Kings/2/6/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Kings/2/9/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/7/9/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/11/8/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/14/13/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/17/13/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/17/16/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/21/13/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/24/19/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/26/6/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/6/5/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/9/17/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/16/10/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/18/5/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/30/3/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/31/17/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/49/14/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/49/15/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/55/15/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/86/13/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/88/3/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/89/48
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/116/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/139/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/141/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/1/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/5/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/7/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/9/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/15/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/15/24
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/23/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/27/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/30/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ecclesiates/9/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Song-of-Solomon/8/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/5/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/28/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/28/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/38/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/38/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/57/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/32/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/32/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hosea/13/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Amos/9/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jonah/2/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Habbakuk/2/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5/22
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5/29
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5/30
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/6/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/10/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/11/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/12/32
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13/22
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13/39
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13/40
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13/49
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/16/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/18/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/18/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/19/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/19/29
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/21/19
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/23/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/23/33
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/24/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/25/41
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/25/46
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/28/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/3/29
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/4/19
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9/43
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9/45
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9/47
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/10/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/10/30
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/11/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1/33
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1/55
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1/70
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/8/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/10/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/10/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/12/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/18/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/18/30
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/20/34
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/20/35
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3/36
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/4/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/4/36
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/5/24
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/5/39
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/40
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/47
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/51
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/54
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/58
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6/68
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8/35
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8/51
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8/52
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/9/32
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/10/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/11/26
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12/34
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12/50
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/13/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/14/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/17/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/17/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/2/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/2/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/3/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/13/46
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/13/48
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/15/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/1/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/1/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/2/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/5/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/6/22
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/6/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/9/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/10/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/11/36
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/12/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16/26
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/1/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/3/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/8/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/10/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/15/55
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/5/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/9/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/11/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/1/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/1/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/6/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/1/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/2/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/2/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/6/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Philippians/4/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Colossians/1/26
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Thessalonians/1/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Thessalonians/2/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/1/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/1/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6/19
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/1/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/2/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/4/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/4/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/1/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/2/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/3/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Philemon/1/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/1/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/1/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/5/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/5/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7/24
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9/26
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/11/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/James/3/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/1/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/1/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/4/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/5/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/5/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/1/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/2/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/2/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/3/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/1/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/2/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/2/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/3/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-John/1/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/22
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/1/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/1/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/4/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/4/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/5/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/5/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/6/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/7/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/10/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/11/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/11/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/14/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/14/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/15/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/17/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/19/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/19/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/21/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/22/5

wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/37
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/42
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/44
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Genesis/44
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Numbers/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Numbers/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Deuteronomy/32
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Samuel/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Samuel/22
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Kings/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Kings/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/24
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Job/26
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/30
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/49
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/49
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/55
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/86
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/88
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/89
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/116
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/139
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Psalms/141
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/27
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Proverbs/30
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ecclesiates/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Song-of-Solomon/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/38
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/38
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Isaiah/57
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/31
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/32
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ezekiel/32
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hosea/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Amos/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jonah/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Habbakuk/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/19
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/19
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/21
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/23
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/24
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/25
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Matthew/28
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Mark/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/18
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Luke/20
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/14
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/John/17
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Acts/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/12
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Romans/16
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/8
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/10
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Corinthians/15
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Corinthians/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Galatians/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Ephesians/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Philippians/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Colossians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Thessalonians/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Thessalonians/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Timothy/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Timothy/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Titus/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Philemon/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/6
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/7
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/9
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/11
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Hebrews/13
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/James/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/4
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-Peter/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-Peter/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/2
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/3
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/1-John/5
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/2-John/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Jude/1/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/1/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/1/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/4/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/4/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/5/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/5/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/6/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/7/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/9/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/10/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/11/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/11/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/14/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/14/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/15/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/17/parallel-French---French-Martin
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/19/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/19/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/20/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/21/parallel-French---French-Martin/strongs-g166
wget -q -S -O - https://stage.aionianbible.org/Bibles/English---Aionian-Bible/Revelation/22/parallel-French---French-Martin/strongs-g166
