echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=AB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ABP
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ABPGRK
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Afr1953
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Alb
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Aleppo
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=AraNAV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=AraSVD
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ASV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Azeri
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BBE
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BeaMRK
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Bela
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BretonNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BSB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BulCarigradNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BulVeren
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BurCBCM
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BurJudson
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=BWE
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ChiNCVs
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ChiUn
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ChiUnL
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ChiUns
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Common
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CopNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CopSahidica
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CopSahidicMSS
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CroSaric
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CzeB21
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CzeCEP
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=CzeCSP
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=DaNT1819
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Darby
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Dari
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=DRC
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=DutSVVA
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=EMTV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Esperanto
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Est
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FarHezareNoh
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FarOPV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FarTPV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FinBiblia
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FinPR
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FinPR92
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FinRK
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FinSTLK2017
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FreBA
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FreGeneve1669
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FreLXXGiguet
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=FreSegond1910
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Geez
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Geneva1599
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerBoLut
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerElb1871
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerElb1905
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerHfa2002
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerLeoNA28
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerLeoRP18
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerNeUe
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerOffBiSt
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerSch
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerTextbibel
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GerZurcher
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=GodsWord
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Haitian
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=HebDelitzsch
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=HebModern
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=HunKNB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=HunRUF
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=HunUj
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ISV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ItaDio
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ItaRive
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=JPS
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Jubilee2000
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Kapingamarangi
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Kekchi
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KhmerNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KJV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KJVA
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KLV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KorHKJV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=KswSKMB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Latvian
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=LEB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=LinVB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=LITV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=LO
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=LtKBB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ManxGaelic
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Maori
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=MKJV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=MonKJV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=MorphGNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NETfree
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NETtext
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NHEB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NHEBJE
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NHEBME
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NldLeuv1548
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NorBroed
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Norsk
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=NorthernAzeri
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Noyes
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=OEB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=OEBcth
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=OrthJBC
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=OSHB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=OxfordTR
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PohnOld
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Pohnpeian
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PolUGdanska
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PorBLivre
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PorBLivreTR
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PorCap
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PorNVA
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=PotLykins
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RKJNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RomCor
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RusMakarij
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RusSynodal
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RusSynodalLIO
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=RusVZh
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SBLGNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SloChraska
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SloOjacano
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=sml_BL_2008
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SomKQA
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SP
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SpaRV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SpaRV1909
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SpaRVG
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SpaTDP
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SpaVNT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SPDSS
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SPE
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SPMT
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SPVar
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SrKDIjekav
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Swahili
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SweFolk
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=SweKarlXII
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Tagalog
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Tausug
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=ThaiKJV
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Tisch
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=TpiKJPB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=TurHADI
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=TurNTB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Uma
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=UrduGeo
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=UrduGeoDeva
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=UrduGeoRoman
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=VieLCCMN
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=VietNVB
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Vulgate_HebPs
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Webster
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=WelBeiblNet
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Weymouth
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=Wulfila
echo "========================"; wget -O - https://crosswire.org/sword/modules/ModInfo.jsp?modName=YLT
