
# wget -l 2 -A jpg -m -p -E -k -K -np -nd -A jpg --accept-regex "/Dore/Images/*.jpg" https://catholic-resources.org/Art/Dore-OT.htm

# wget -l 2 -nd -A jpg --accept-regex "https://catholic-resources.org/Dore/Images/*.jpg" https://catholic-resources.org/Art/Dore-OT.htm

wget https://catholic-resources.org/Dore/Images/OT-001.jpg
wget https://catholic-resources.org/Dore/Images/OT-002.jpg
wget https://catholic-resources.org/Dore/Images/OT-003.jpg
wget https://catholic-resources.org/Dore/Images/OT-004.jpg
wget https://catholic-resources.org/Dore/Images/OT-005.jpg
wget https://catholic-resources.org/Dore/Images/OT-006.jpg
wget https://catholic-resources.org/Dore/Images/OT-007.jpg
wget https://catholic-resources.org/Dore/Images/OT-008.jpg
wget https://catholic-resources.org/Dore/Images/OT-009.jpg
wget https://catholic-resources.org/Dore/Images/OT-010.jpg
wget https://catholic-resources.org/Dore/Images/OT-011.jpg
wget https://catholic-resources.org/Dore/Images/OT-012.jpg
wget https://catholic-resources.org/Dore/Images/OT-013.jpg
wget https://catholic-resources.org/Dore/Images/OT-014.jpg
wget https://catholic-resources.org/Dore/Images/OT-015.jpg
wget https://catholic-resources.org/Dore/Images/OT-016.jpg
wget https://catholic-resources.org/Dore/Images/OT-017.jpg
wget https://catholic-resources.org/Dore/Images/OT-018.jpg
wget https://catholic-resources.org/Dore/Images/OT-019.jpg
wget https://catholic-resources.org/Dore/Images/OT-020.jpg
wget https://catholic-resources.org/Dore/Images/OT-021.jpg
wget https://catholic-resources.org/Dore/Images/OT-022.jpg
wget https://catholic-resources.org/Dore/Images/OT-023.jpg
wget https://catholic-resources.org/Dore/Images/OT-024.jpg
wget https://catholic-resources.org/Dore/Images/OT-025.jpg
wget https://catholic-resources.org/Dore/Images/OT-026.jpg
wget https://catholic-resources.org/Dore/Images/OT-027.jpg
wget https://catholic-resources.org/Dore/Images/OT-028.jpg
wget https://catholic-resources.org/Dore/Images/OT-029.jpg
wget https://catholic-resources.org/Dore/Images/OT-030.jpg
wget https://catholic-resources.org/Dore/Images/OT-031.jpg
wget https://catholic-resources.org/Dore/Images/OT-032.jpg
wget https://catholic-resources.org/Dore/Images/OT-033.jpg
wget https://catholic-resources.org/Dore/Images/OT-034.jpg
wget https://catholic-resources.org/Dore/Images/OT-035.jpg
wget https://catholic-resources.org/Dore/Images/OT-036.jpg
wget https://catholic-resources.org/Dore/Images/OT-037.jpg
wget https://catholic-resources.org/Dore/Images/OT-038.jpg
wget https://catholic-resources.org/Dore/Images/OT-039.jpg
wget https://catholic-resources.org/Dore/Images/OT-040.jpg
wget https://catholic-resources.org/Dore/Images/OT-041.jpg
wget https://catholic-resources.org/Dore/Images/OT-042.jpg
wget https://catholic-resources.org/Dore/Images/OT-043.jpg
wget https://catholic-resources.org/Dore/Images/OT-044.jpg
wget https://catholic-resources.org/Dore/Images/OT-045.jpg
wget https://catholic-resources.org/Dore/Images/OT-046.jpg
wget https://catholic-resources.org/Dore/Images/OT-048.jpg
wget https://catholic-resources.org/Dore/Images/OT-049.jpg
wget https://catholic-resources.org/Dore/Images/OT-050.jpg
wget https://catholic-resources.org/Dore/Images/OT-051.jpg
wget https://catholic-resources.org/Dore/Images/OT-052.jpg
wget https://catholic-resources.org/Dore/Images/OT-053.jpg
wget https://catholic-resources.org/Dore/Images/OT-047.jpg
wget https://catholic-resources.org/Dore/Images/OT-054.jpg
wget https://catholic-resources.org/Dore/Images/OT-055.jpg
wget https://catholic-resources.org/Dore/Images/OT-056.jpg
wget https://catholic-resources.org/Dore/Images/OT-057.jpg
wget https://catholic-resources.org/Dore/Images/OT-058.jpg
wget https://catholic-resources.org/Dore/Images/OT-059.jpg
wget https://catholic-resources.org/Dore/Images/OT-060.jpg
wget https://catholic-resources.org/Dore/Images/OT-061.jpg
wget https://catholic-resources.org/Dore/Images/OT-062.jpg
wget https://catholic-resources.org/Dore/Images/OT-063.jpg
wget https://catholic-resources.org/Dore/Images/OT-064.jpg
wget https://catholic-resources.org/Dore/Images/OT-065.jpg
wget https://catholic-resources.org/Dore/Images/OT-066.jpg
wget https://catholic-resources.org/Dore/Images/OT-067.jpg
wget https://catholic-resources.org/Dore/Images/OT-068.jpg
wget https://catholic-resources.org/Dore/Images/OT-069.jpg
wget https://catholic-resources.org/Dore/Images/OT-070.jpg
wget https://catholic-resources.org/Dore/Images/OT-071.jpg
wget https://catholic-resources.org/Dore/Images/OT-072.jpg
wget https://catholic-resources.org/Dore/Images/OT-073.jpg
wget https://catholic-resources.org/Dore/Images/OT-074.jpg
wget https://catholic-resources.org/Dore/Images/OT-075.jpg
wget https://catholic-resources.org/Dore/Images/OT-076.jpg
wget https://catholic-resources.org/Dore/Images/OT-077.jpg
wget https://catholic-resources.org/Dore/Images/OT-078.jpg
wget https://catholic-resources.org/Dore/Images/OT-079.jpg
wget https://catholic-resources.org/Dore/Images/OT-080.jpg
wget https://catholic-resources.org/Dore/Images/OT-081.jpg
wget https://catholic-resources.org/Dore/Images/OT-083.jpg
wget https://catholic-resources.org/Dore/Images/OT-084.jpg
wget https://catholic-resources.org/Dore/Images/OT-085.jpg
wget https://catholic-resources.org/Dore/Images/OT-086.jpg
wget https://catholic-resources.org/Dore/Images/OT-087.jpg
wget https://catholic-resources.org/Dore/Images/OT-089.jpg
wget https://catholic-resources.org/Dore/Images/OT-090.jpg
wget https://catholic-resources.org/Dore/Images/OT-091.jpg
wget https://catholic-resources.org/Dore/Images/OT-094.jpg
wget https://catholic-resources.org/Dore/Images/OT-095.jpg
wget https://catholic-resources.org/Dore/Images/OT-096.jpg
wget https://catholic-resources.org/Dore/Images/OT-097.jpg
wget https://catholic-resources.org/Dore/Images/OT-098.jpg
wget https://catholic-resources.org/Dore/Images/OT-100.jpg
wget https://catholic-resources.org/Dore/Images/OT-101.jpg
wget https://catholic-resources.org/Dore/Images/OT-102.jpg
wget https://catholic-resources.org/Dore/Images/OT-103.jpg
wget https://catholic-resources.org/Dore/Images/OT-104.jpg
wget https://catholic-resources.org/Dore/Images/OT-105.jpg
wget https://catholic-resources.org/Dore/Images/OT-106.jpg
wget https://catholic-resources.org/Dore/Images/OT-108.jpg
wget https://catholic-resources.org/Dore/Images/OT-112.jpg
wget https://catholic-resources.org/Dore/Images/OT-113.jpg
wget https://catholic-resources.org/Dore/Images/OT-082.jpg
wget https://catholic-resources.org/Dore/Images/OT-088.jpg
wget https://catholic-resources.org/Dore/Images/OT-092.jpg
wget https://catholic-resources.org/Dore/Images/OT-093.jpg
wget https://catholic-resources.org/Dore/Images/OT-099.jpg
wget https://catholic-resources.org/Dore/Images/OT-107.jpg
wget https://catholic-resources.org/Dore/Images/OT-130.jpg
wget https://catholic-resources.org/Dore/Images/OT-135.jpg
wget https://catholic-resources.org/Dore/Images/OT-131.jpg
wget https://catholic-resources.org/Dore/Images/OT-132.jpg
wget https://catholic-resources.org/Dore/Images/OT-134.jpg
wget https://catholic-resources.org/Dore/Images/OT-133.jpg
wget https://catholic-resources.org/Dore/Images/OT-140.jpg
wget https://catholic-resources.org/Dore/Images/OT-141.jpg
wget https://catholic-resources.org/Dore/Images/OT-142.jpg
wget https://catholic-resources.org/Dore/Images/OT-143.jpg
wget https://catholic-resources.org/Dore/Images/OT-119.jpg
wget https://catholic-resources.org/Dore/Images/OT-120.jpg
wget https://catholic-resources.org/Dore/Images/OT-121.jpg
wget https://catholic-resources.org/Dore/Images/OT-144.jpg
wget https://catholic-resources.org/Dore/Images/OT-149.jpg
wget https://catholic-resources.org/Dore/Images/OT-150.jpg
wget https://catholic-resources.org/Dore/Images/OT-151.jpg
wget https://catholic-resources.org/Dore/Images/OT-152.jpg
wget https://catholic-resources.org/Dore/Images/OT-153.jpg
wget https://catholic-resources.org/Dore/Images/OT-154.jpg
wget https://catholic-resources.org/Dore/Images/OT-155.jpg
wget https://catholic-resources.org/Dore/Images/OT-156.jpg
wget https://catholic-resources.org/Dore/Images/OT-157.jpg
wget https://catholic-resources.org/Dore/Images/OT-158.jpg
wget https://catholic-resources.org/Dore/Images/OT-159.jpg
wget https://catholic-resources.org/Dore/Images/OT-160.jpg
wget https://catholic-resources.org/Dore/Images/OT-136.jpg
wget https://catholic-resources.org/Dore/Images/OT-137.jpg
wget https://catholic-resources.org/Dore/Images/OT-110.jpg
wget https://catholic-resources.org/Dore/Images/OT-127.jpg
wget https://catholic-resources.org/Dore/Images/OT-128.jpg
wget https://catholic-resources.org/Dore/Images/OT-114.jpg
wget https://catholic-resources.org/Dore/Images/OT-115.jpg
wget https://catholic-resources.org/Dore/Images/OT-116.jpg
wget https://catholic-resources.org/Dore/Images/OT-145.jpg
wget https://catholic-resources.org/Dore/Images/OT-117.jpg
wget https://catholic-resources.org/Dore/Images/OT-118.jpg
wget https://catholic-resources.org/Dore/Images/OT-122.jpg
wget https://catholic-resources.org/Dore/Images/OT-123.jpg
wget https://catholic-resources.org/Dore/Images/OT-124.jpg
wget https://catholic-resources.org/Dore/Images/OT-125.jpg
wget https://catholic-resources.org/Dore/Images/OT-126.jpg
wget https://catholic-resources.org/Dore/Images/OT-146.jpg
wget https://catholic-resources.org/Dore/Images/OT-147.jpg
wget https://catholic-resources.org/Dore/Images/OT-148.jpg
wget https://catholic-resources.org/Dore/Images/OT-109.jpg
wget https://catholic-resources.org/Dore/Images/OT-138.jpg
wget https://catholic-resources.org/Dore/Images/OT-139.jpg
wget https://catholic-resources.org/Dore/Images/OT-111.jpg
wget https://catholic-resources.org/Dore/Images/OT-129.jpg
wget https://catholic-resources.org/Dore/Images/NT-163.jpg
wget https://catholic-resources.org/Dore/Images/NT-164.jpg
wget https://catholic-resources.org/Dore/Images/NT-165.jpg
wget https://catholic-resources.org/Dore/Images/NT-175.jpg
wget https://catholic-resources.org/Dore/Images/NT-178.jpg
wget https://catholic-resources.org/Dore/Images/NT-182.jpg
wget https://catholic-resources.org/Dore/Images/NT-184.jpg
wget https://catholic-resources.org/Dore/Images/NT-186.jpg
wget https://catholic-resources.org/Dore/Images/NT-188.jpg
wget https://catholic-resources.org/Dore/Images/NT-198.jpg
wget https://catholic-resources.org/Dore/Images/NT-200.jpg
wget https://catholic-resources.org/Dore/Images/NT-203.jpg
wget https://catholic-resources.org/Dore/Images/NT-208.jpg
wget https://catholic-resources.org/Dore/Images/NT-209.jpg
wget https://catholic-resources.org/Dore/Images/NT-215.jpg
wget https://catholic-resources.org/Dore/Images/NT-220.jpg
wget https://catholic-resources.org/Dore/Images/NT-167.jpg
wget https://catholic-resources.org/Dore/Images/NT-172.jpg
wget https://catholic-resources.org/Dore/Images/NT-176.jpg
wget https://catholic-resources.org/Dore/Images/NT-179.jpg
wget https://catholic-resources.org/Dore/Images/NT-187.jpg
wget https://catholic-resources.org/Dore/Images/NT-192.jpg
wget https://catholic-resources.org/Dore/Images/NT-201.jpg
wget https://catholic-resources.org/Dore/Images/NT-205.jpg
wget https://catholic-resources.org/Dore/Images/NT-207.jpg
wget https://catholic-resources.org/Dore/Images/NT-211.jpg
wget https://catholic-resources.org/Dore/Images/NT-217.jpg
wget https://catholic-resources.org/Dore/Images/NT-161.jpg
wget https://catholic-resources.org/Dore/Images/NT-162.jpg
wget https://catholic-resources.org/Dore/Images/NT-166.jpg
wget https://catholic-resources.org/Dore/Images/NT-169.jpg
wget https://catholic-resources.org/Dore/Images/NT-173.jpg
wget https://catholic-resources.org/Dore/Images/NT-174.jpg
wget https://catholic-resources.org/Dore/Images/NT-177.jpg
wget https://catholic-resources.org/Dore/Images/NT-180.jpg
wget https://catholic-resources.org/Dore/Images/NT-190.jpg
wget https://catholic-resources.org/Dore/Images/NT-191.jpg
wget https://catholic-resources.org/Dore/Images/NT-181.jpg
wget https://catholic-resources.org/Dore/Images/NT-183.jpg
wget https://catholic-resources.org/Dore/Images/NT-193.jpg
wget https://catholic-resources.org/Dore/Images/NT-194.jpg
wget https://catholic-resources.org/Dore/Images/NT-195.jpg
wget https://catholic-resources.org/Dore/Images/NT-196.jpg
wget https://catholic-resources.org/Dore/Images/NT-199.jpg
wget https://catholic-resources.org/Dore/Images/NT-204.jpg
wget https://catholic-resources.org/Dore/Images/NT-212.jpg
wget https://catholic-resources.org/Dore/Images/NT-214.jpg
wget https://catholic-resources.org/Dore/Images/NT-216.jpg
wget https://catholic-resources.org/Dore/Images/NT-221.jpg
wget https://catholic-resources.org/Dore/Images/NT-223.jpg
wget https://catholic-resources.org/Dore/Images/NT-168.jpg
wget https://catholic-resources.org/Dore/Images/NT-170.jpg
wget https://catholic-resources.org/Dore/Images/NT-171.jpg
wget https://catholic-resources.org/Dore/Images/NT-185.jpg
wget https://catholic-resources.org/Dore/Images/NT-189.jpg
wget https://catholic-resources.org/Dore/Images/NT-197.jpg
wget https://catholic-resources.org/Dore/Images/NT-202.jpg
wget https://catholic-resources.org/Dore/Images/NT-206.jpg
wget https://catholic-resources.org/Dore/Images/NT-210.jpg
wget https://catholic-resources.org/Dore/Images/NT-213.jpg
wget https://catholic-resources.org/Dore/Images/NT-218.jpg
wget https://catholic-resources.org/Dore/Images/NT-219.jpg
wget https://catholic-resources.org/Dore/Images/NT-222.jpg
wget https://catholic-resources.org/Dore/Images/NT-224.jpg
wget https://catholic-resources.org/Dore/Images/NT-225.jpg
wget https://catholic-resources.org/Dore/Images/NT-226.jpg
wget https://catholic-resources.org/Dore/Images/NT-227.jpg
wget https://catholic-resources.org/Dore/Images/NT-228.jpg
wget https://catholic-resources.org/Dore/Images/NT-229.jpg
wget https://catholic-resources.org/Dore/Images/NT-230.jpg
wget https://catholic-resources.org/Dore/Images/NT-231.jpg
wget https://catholic-resources.org/Dore/Images/NT-232.jpg
wget https://catholic-resources.org/Dore/Images/NT-233.jpg
wget https://catholic-resources.org/Dore/Images/NT-234.jpg
wget https://catholic-resources.org/Dore/Images/NT-235.jpg
wget https://catholic-resources.org/Dore/Images/NT-236.jpg
wget https://catholic-resources.org/Dore/Images/NT-237.jpg
wget https://catholic-resources.org/Dore/Images/NT-238.jpg
wget https://catholic-resources.org/Dore/Images/NT-239.jpg
wget https://catholic-resources.org/Dore/Images/NT-240.jpg
wget https://catholic-resources.org/Dore/Images/NT-241.jpg

